# Generated by Django 4.2 on 2026-03-27 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('alert_type', models.CharField(choices=[('ac', 'AC ON in empty room'), ('lights', 'Lights ON in empty room'), ('both', 'Both AC and Lights ON')], max_length=20)),
                ('room_id', models.CharField(max_length=50)),
                ('temperature', models.FloatField()),
                ('lux', models.FloatField()),
                ('sound_level', models.FloatField()),
                ('motion_detected', models.BooleanField()),
                ('sent_via', models.CharField(default='web', max_length=20)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RoomStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=50, unique=True)),
                ('is_occupied', models.BooleanField(default=False)),
                ('last_occupied_time', models.DateTimeField(blank=True, null=True)),
                ('last_empty_time', models.DateTimeField(blank=True, null=True)),
                ('empty_since', models.DateTimeField(blank=True, null=True)),
                ('alert_sent', models.BooleanField(default=False)),
                ('alert_sent_time', models.DateTimeField(blank=True, null=True)),
                ('current_temperature', models.FloatField(default=0)),
                ('current_lux', models.FloatField(default=0)),
                ('current_sound', models.FloatField(default=0)),
                ('current_distance', models.IntegerField(default=999)),
                ('ac_on', models.BooleanField(default=False)),
                ('lights_on', models.BooleanField(default=False)),
                ('motion_detected', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('accel_x', models.FloatField(default=0)),
                ('accel_y', models.FloatField(default=0)),
                ('accel_z', models.FloatField(default=0)),
                ('vibration', models.FloatField(default=0)),
                ('motion_detected', models.BooleanField(default=False)),
                ('temperature', models.FloatField(default=0)),
                ('pressure', models.FloatField(default=0)),
                ('lux', models.FloatField(default=0)),
                ('light_on', models.BooleanField(default=False)),
                ('sound_level', models.FloatField(default=0)),
                ('distance', models.IntegerField(default=999)),
                ('room_id', models.CharField(default='CLASSROOM_101', max_length=50)),
                ('occupancy', models.CharField(default='unknown', max_length=20)),
                ('wifi_rssi', models.IntegerField(default=0)),
                ('ac_state', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='sensordata',
            index=models.Index(fields=['-timestamp'], name='api_sensord_timesta_95cb2f_idx'),
        ),
        migrations.AddIndex(
            model_name='sensordata',
            index=models.Index(fields=['occupancy'], name='api_sensord_occupan_8acb94_idx'),
        ),
    ]
