# Generated by Django 4.2 on 2026-04-06 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomstatus',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomstatus',
            name='last_data_received',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
