# Generated by Django 4.2 on 2026-04-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_roomstatus_is_online_roomstatus_last_data_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomstatus',
            name='current_vibration',
            field=models.FloatField(default=0),
        ),
    ]
